/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/modals/GridScoreExportModal copy.vue')['default']
    GridScoreExportModal: typeof import('./components/modals/GridScoreExportModal.vue')['default']
    GridScoreInfoModal: typeof import('./components/modals/GridScoreInfoModal.vue')['default']
    ImageProcessor: typeof import('./components/ImageProcessor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./components/modals/SettingsModal.vue')['default']
  }
}
